name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - env:
        DEEPL_AUTH_KEY: ${{ secrets.DEEPL_AUTH_KEY }}
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
        bundler-cache: true
    - name: Run the RSpec tests
      run: bundle exec rake spec
